Repository woowacourse-bot/discord-bot, pull requests merged in 2023-10, with the labels that each got.

#4 feat: 채널 관리 기능 봇 추가
  index.js
  package-lock.json
  package.json
Labels: feat

#5 Docs: `README.md` 초안 작성
  README.md
Labels: documentation

#9 feat: 프로젝트 환경변수 설정
  .gitignore
  README.md
  env.sample
  package.json
  src/index.js
Labels: documentation, feat

#16 chore: `dotenv/config` import 관련 eslint 설정 수정
  .eslintrc.cjs
  src/index.js
Labels: chore
